import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  fetchPublishedStoriesList,
  fetchPublishedStory,
  type PublishedStoryListItem,
} from '../services/storyServices';
import { useEntitlements } from '../context/EntitlementsContext';
import { useAuth } from '../context/AuthContext';
import { useCatalog } from '../context/CatalogContext';

export type StoryCategory = 'general' | 'news';

export interface StoryGroup {
  slug: string;           // URL-friendly name, e.g. "leo"
  title: string;
  description: string;
  character: string;
  totalTracks: number;
  coverEmoji: string;
  /**
   * 4:5 cover art for the story card in List.tsx, cropped from the story's own
   * first comic page. Generated by scripts/make-covers.py — run it after adding
   * a story so the card gets art instead of the halftone + emoji fallback.
   * Stories without one (news placeholders, anything built in the Story
   * Builder) fall back to coverEmoji, which is by design, not a gap.
   */
  cover?: string;
  /** Which heading/section this story is grouped under in List.tsx. Defaults to 'general'. */
  category: StoryCategory;
  /**
   * Paywall state, decided by the SERVER and carried on the list response.
   */
  locked?: boolean;
  /** Any one of these SKUs unlocks it, smallest scope first. */
  requiredSkus?: string[];
  /** When locked: parts 1..freeParts play in full. */
  freeParts?: number;
  /** When locked and set: part 1 is a timed preview of this many seconds. */
  previewSeconds?: number | null;
}

export type DifficultySlug = 'easy' | 'medium' | 'hard';

/**
 * Each level's character art, used when a story has no cover of its own.
 *
 * Every story on a level stars the same character, so their own comic is the
 * honest stand-in — far better than the halftone placeholder, and it means the
 * nine extension-pack stories can ship without waiting on nine new comics to be
 * drawn. StoryCard crops each card differently (deterministically, from the
 * slug), so four Leo stories do not render as four identical cards.
 *
 * News stories are deliberately excluded below: they are not about the
 * character, and giving them his portrait would say something untrue about
 * what is inside. They keep the halftone + newspaper icon.
 */
export const CHARACTER_COVER: Record<DifficultySlug, string> = {
  easy: '/assets/covers/leo.jpg',
  medium: '/assets/covers/maya.jpg',
  hard: '/assets/covers/daniel.jpg',
};

/** A story's cover, falling back to its level's character art. */
export const coverFor = (
  difficulty: DifficultySlug,
  category: StoryCategory,
  ownCover?: string,
): string | undefined =>
  ownCover ?? (category === 'news' ? undefined : CHARACTER_COVER[difficulty]);

/**
 * @param fallbackCategory the static entry's category, used when the DB story
 *   has no opinion. A published DB story REPLACES its static counterpart
 *   wholesale, so hardcoding 'general' here silently moved every news story to
 *   the Stories shelf the moment it was published. Stories imported before the
 *   category field existed carry null, and this is what keeps them in place
 *   without a data migration.
 */
export type AppLocale = 'en' | 'ru';

/**
 * Which locale's text to show. i18next language codes can carry a region
 * ("ru-RU"), so match on the prefix rather than equality — the app only ever
 * ships these two bundles.
 */
export function useAppLocale(): AppLocale {
  const { i18n } = useTranslation();
  return i18n.language?.toLowerCase().startsWith('ru') ? 'ru' : 'en';
}

export function dbStoryToGroup(
  story: {
    storyId: string;
    storyName: string;
    description: string;
    localized?: { title: { en: string; ru: string }; description: { en: string; ru: string } } | null;
    characterIcon: string;
    category?: StoryCategory | null;
    coverUrl?: string | null;
    totalParts: number;
    locked?: boolean;
    requiredSkus?: string[];
    freeParts?: number;
    previewSeconds?: number | null;
  },
  difficulty: DifficultySlug,
  locale: AppLocale = 'en',
): StoryGroup {
  const category = story.category ?? 'general';
  return {
    slug: story.storyId,
    // Per-locale text wins; storyName is the admin-facing identifier, kept
    // only as the last resort for a story whose text was never written.
    title: story.localized?.title?.[locale]?.trim() || story.storyName,
    description: story.localized?.description?.[locale]?.trim() || story.description,
    character: story.storyName,
    totalTracks: story.totalParts,
    coverEmoji: story.characterIcon,
    category,
    cover: coverFor(difficulty, category, story.coverUrl ?? undefined),
    locked: story.locked ?? false,
    requiredSkus: story.requiredSkus ?? [],
    freeParts: story.freeParts,
    previewSeconds: story.previewSeconds ?? null,
  };
}

/**
 * What the published-list endpoint last said, per difficulty, for the life of
 * the tab.
 *
 * This exists so a SECOND visit to a level costs no skeleton: the answer is
 * already here on the very first render, and the page paints its final state
 * straight away. Entering a level, going back, and entering it again is the
 * single most common path through this app, so the cheap case should be the
 * common one.
 *
 * It is stale-while-revalidate, not a plain cache — every mount still refetches
 * in the background and overwrites this. So a story published from the Story
 * Builder shows up on the next navigation rather than needing a reload, and the
 * worst a stale entry can do is render one frame of a list that was correct a
 * moment ago. Nothing here is an entitlement decision: `locked` is the server's
 * word, and a cached `locked: false` cannot unlock anything, because the player
 * asks the server for audio and gets refused independently of this.
 */
//
// Keyed by WHO asked as well as which level. The response carries each story's
// lock state for the caller, so a list cached while signed out, or signed in as
// someone else, painted that person's padlocks first and then the real ones.
const publishedListCache = new Map<
  string,
  { stories: PublishedStoryListItem[]; hidden: Set<string> }
>();

/**
 * The newest request per cache key. Responses can arrive out of order — React
 * StrictMode mounts twice, and a slow request can finish after a quick
 * navigation away and back — and an overtaken answer must not overwrite the
 * cache, or the NEXT visit opens on a shelf that was already out of date.
 */
const latestRequest = new Map<string, number>();
let requestSeq = 0;

// Stable identities for "the server has not answered yet". A fresh `[]` or
// `new Set()` is a different object every time it is evaluated, so handing one
// to setState always counts as a change — which bought a whole extra render
// that repainted the identical skeleton. Neither is ever mutated: a resolved
// fetch builds its own Set.
const NO_STORIES: PublishedStoryListItem[] = [];
const NO_HIDDEN: Set<string> = new Set();

/**
 * The level's stories, plus whether the server has answered yet.
 *
 * `loading` is the whole point. Without it a page has no way to tell the
 * difference between "these are the stories" and "these are the stories I
 * could name before asking", and every caller painted the latter: the static
 * catalogue rendered first, unlocked and complete, then snapped to the real
 * list a moment later as padlocks appeared, hidden stories vanished and
 * published ones arrived. The data was never wrong, it was just shown before
 * it was true.
 */
export function useStoryGroupsWithStatus(
  difficulty: DifficultySlug,
): { stories: StoryGroup[]; loading: boolean } {
  const locale = useAppLocale();
  const { entitlementsLoading } = useEntitlements();
  const catalog = useCatalog();
  const { user } = useAuth();
  const cacheKey = `${user?.id ?? 'guest'}:${difficulty}`;
  // Seeded from the cache in the initialiser rather than by an effect, which is
  // what makes a repeat visit flicker-free: by the time the first render runs,
  // the state already holds the answer.
  const seed = publishedListCache.get(cacheKey);
  const [dbStories, setDbStories] = useState<PublishedStoryListItem[]>(
    () => seed?.stories ?? NO_STORIES,
  );
  const [hidden, setHidden] = useState<Set<string>>(() => seed?.hidden ?? NO_HIDDEN);
  const [loading, setLoading] = useState(() => !seed);

  // Switching levels resets during render, not in an effect.
  //
  // /levels/easy → /levels/medium is the same route element with a new param,
  // so React keeps this component mounted. An effect would only correct the
  // state AFTER a frame had been painted, and that frame is medium's static
  // catalogue merged with easy's published rows — a list that has never been
  // true. Assigning during render makes React throw the in-progress output
  // away and start again before anything reaches the screen.
  // Signing in or out changes the key too, and gets the same treatment.
  const [loadedFor, setLoadedFor] = useState<string>(cacheKey);
  if (loadedFor !== cacheKey) {
    const known = publishedListCache.get(cacheKey);
    setLoadedFor(cacheKey);
    setDbStories(known?.stories ?? NO_STORIES);
    setHidden(known?.hidden ?? NO_HIDDEN);
    // A level already in the cache never drops back to a skeleton.
    setLoading(!known);
  }

  useEffect(() => {
    let cancelled = false;
    requestSeq += 1;
    const requestId = requestSeq;
    latestRequest.set(cacheKey, requestId);

    fetchPublishedStoriesList(difficulty).then(({ stories, hidden: hiddenIds, ok }) => {
      // Overtaken by a newer request for the same list: this is older news.
      if (latestRequest.get(cacheKey) !== requestId) return;

      const known = publishedListCache.get(cacheKey);
      // A failed fetch comes back empty. Painting that over a list we already
      // hold swapped the real shelf for the bare static catalogue until the
      // next successful request put it back.
      if (!ok && known) {
        if (!cancelled) setLoading(false);
        return;
      }

      const hiddenSet = new Set(hiddenIds);
      // Cached even if this hook has unmounted in the meantime — but only a
      // real answer, never a failure.
      if (ok) publishedListCache.set(cacheKey, { stories, hidden: hiddenSet });
      if (cancelled) return;
      setDbStories(stories);
      setHidden(hiddenSet);
      setLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, [difficulty, cacheKey]);

  // Memoised: a new array per render would make every card's props new.
  const stories = useMemo(
    () => visibleStoryGroups(dbStories, difficulty, locale, hidden),
    [dbStories, difficulty, locale, hidden],
  );

  // A lock drawn before ownership is known is a lock that flickers off.
  // A price or a padlock drawn before the catalog lands is one that changes
  // under the reader, so the catalog is part of "not ready yet" too.
  return { stories, loading: loading || entitlementsLoading || catalog.catalogLoading };
}

/**
 * What a learner sees on a level shelf: the server's published stories, in
 * its order, minus the ones an admin unlisted. Pure, so the rule can be tested
 * without mounting a hook.
 */
export function visibleStoryGroups(
  stories: Parameters<typeof dbStoryToGroup>[0][],
  difficulty: DifficultySlug,
  locale: AppLocale,
  hidden: Set<string>,
): StoryGroup[] {
  return stories
    .map((s) => dbStoryToGroup(s, difficulty, locale))
    .filter((g) => !hidden.has(g.slug));
}

/**
 * One story by slug. `loading` is true until the server has answered; a
 * missing storyGroup after that means "not found" (or hidden).
 */
export function useStoryGroup(
  difficulty: DifficultySlug,
  slug: string,
): { storyGroup: StoryGroup | undefined; loading: boolean } {
  const [dbGroup, setDbGroup] = useState<StoryGroup | undefined>(undefined);
  const [dbChecked, setDbChecked] = useState(false);
  const [hidden, setHidden] = useState<Set<string>>(() => new Set());
  const locale = useAppLocale();

  useEffect(() => {
    let cancelled = false;
    setDbChecked(false);
    // Both: a published story can still be hidden from learners.
    Promise.all([
      fetchPublishedStory(difficulty, slug),
      fetchPublishedStoriesList(difficulty),
    ])
      .then(([story, list]) => {
        if (cancelled) return;
        setDbGroup(story ? dbStoryToGroup(story, difficulty, locale) : undefined);
        setHidden(new Set(list.hidden));
        setDbChecked(true);
      })
      .catch(() => {
        if (!cancelled) setDbChecked(true);
      });
    return () => {
      cancelled = true;
    };
  }, [difficulty, slug, locale]);

  return {
    storyGroup: dbGroup && hidden.has(dbGroup.slug) ? undefined : dbGroup,
    loading: !dbChecked,
  };
}
