import { TFunction } from 'i18next';
import { useEffect, useState } from 'react';
import {
  fetchPublishedStoriesList,
  fetchPublishedStory,
  type PublishedStoryListItem,
} from '../services/storyServices';

export type StoryCategory = 'general' | 'news';

export interface StoryGroup {
  slug: string;           // URL-friendly name, e.g. "leo"
  title: string;
  description: string;
  character: string;
  totalTracks: number;
  coverEmoji: string;
  /**
   * 4:5 cover art for the story card in List.tsx, cropped from the story's own
   * first comic page. Generated by scripts/make-covers.py — run it after adding
   * a story so the card gets art instead of the halftone + emoji fallback.
   * Stories without one (news placeholders, anything built in the Story
   * Builder) fall back to coverEmoji, which is by design, not a gap.
   */
  cover?: string;
  /** Which heading/section this story is grouped under in List.tsx. Defaults to 'general'. */
  category: StoryCategory;
}

export type DifficultySlug = 'easy' | 'medium' | 'hard';
// Only non-translatable fields live here
type StoryGroupRaw = Omit<StoryGroup, 'title' | 'description' | 'category'> & {
  category?: StoryCategory;
};

const storyGroupsRaw: Record<DifficultySlug, StoryGroupRaw[]> = {
  easy: [
    { slug: 'leo', character: 'Leo', totalTracks: 10, coverEmoji: '🧑', cover: '/assets/covers/leo.jpg' },
    // totalTracks must match the real length of the track array in
    // audiodata/audioDataLeoAdditional.ts — a third track is drafted there but
    // commented out, and claiming 3 here meant progress could never reach 100%.
    { slug: 'leo-additional',    character: 'Leo',    totalTracks: 2, coverEmoji: '🧑', cover: '/assets/covers/leo-additional.jpg' },
    // Placeholder "News and Interesting things" group — students listen to a news
    // source/article first, then get a story connected to it. No real audio/text yet;
    // fill in totalTracks, coverEmoji, and src/modules/audiodata placeholder tracks
    // once content is ready.
    { slug: 'news-roland-garros', character: 'Leo', totalTracks: 2, coverEmoji: '📰', category: 'news', cover: '/assets/covers/news-roland-garros.jpg' },
    // No artwork yet, so no cover — this one keeps the halftone + emoji card.
    { slug: 'news-family-visit',  character: 'Leo', totalTracks: 2, coverEmoji: '📰', category: 'news' },
    { slug: 'news-grazing-board', character: 'Leo', totalTracks: 2, coverEmoji: '📰', category: 'news', cover: '/assets/covers/news-grazing-board.jpg' },
  ],
  medium: [
    { slug: 'maya',   character: 'Maya',   totalTracks: 10, coverEmoji: '👩', cover: '/assets/covers/maya.jpg' },
  ],
  hard: [
    { slug: 'daniel', character: 'Daniel', totalTracks: 10, coverEmoji: '👨', cover: '/assets/covers/daniel.jpg' },
  ],
};

export const getStoryGroups = (diff: DifficultySlug, t: TFunction): StoryGroup[] =>
  storyGroupsRaw[diff].map(story => ({
    ...story,
    category:    story.category ?? 'general',
    title:       t(`stories.${diff}.${story.slug}.title`),
    description: t(`stories.${diff}.${story.slug}.description`),
  }));

// Single-story lookup — built on the same translated data as getStoryGroups,
// so a story's title/description never drifts from what List.tsx shows.
export const getStoryGroup = (
  difficulty: DifficultySlug,
  slug: string,
  t: TFunction,
): StoryGroup | undefined =>
  getStoryGroups(difficulty, t).find(group => group.slug === slug);

// ── DB-backed story fallback ────────────────────────────────────────────────
// Static stories (leo, leo-additional, maya, daniel, the news placeholders)
// are always available synchronously from the functions above, so these
// hooks return that same data immediately (no loading flash for existing
// content) and swap in a published DB-backed story once fetched — a DB
// story *overrides* its static counterpart by slug (imported+published
// stories replace the built-in entry instead of appearing twice), matching
// the whole-story "DB wins once published" precedence in the backend's
// helpers/storyLookup.js.

/**
 * @param fallbackCategory the static entry's category, used when the DB story
 *   has no opinion. A published DB story REPLACES its static counterpart
 *   wholesale, so hardcoding 'general' here silently moved every news story to
 *   the Stories shelf the moment it was published. Stories imported before the
 *   category field existed carry null, and this is what keeps them in place
 *   without a data migration.
 */
function dbStoryToGroup(
  story: {
    storyId: string;
    storyName: string;
    description: string;
    characterIcon: string;
    category?: StoryCategory | null;
    coverUrl?: string | null;
    totalParts: number;
  },
  fallbackCategory: StoryCategory = 'general',
  fallbackCover?: string,
): StoryGroup {
  return {
    slug: story.storyId,
    title: story.storyName,
    description: story.description,
    character: story.storyName,
    totalTracks: story.totalParts,
    coverEmoji: story.characterIcon,
    category: story.category ?? fallbackCategory,
    // Same fallback as the category, for the same reason: publishing replaces
    // the static entry, so without this the card loses its art and drops back
    // to the halftone + emoji placeholder.
    cover: story.coverUrl ?? fallbackCover,
  };
}

export function useStoryGroups(difficulty: DifficultySlug, t: TFunction): StoryGroup[] {
  const staticGroups = getStoryGroups(difficulty, t);
  // The RAW rows are held in state and adapted during render, not in the
  // effect: adapting needs the static entry's category as a fallback, and
  // reaching for staticGroups inside the effect would either capture a stale
  // copy or, if listed as a dependency, refetch on every render since
  // getStoryGroups builds a new array each time.
  const [dbStories, setDbStories] = useState<PublishedStoryListItem[]>([]);
  const [hidden, setHidden] = useState<Set<string>>(() => new Set());

  useEffect(() => {
    let cancelled = false;
    fetchPublishedStoriesList(difficulty).then(({ stories, hidden: hiddenIds }) => {
      if (cancelled) return;
      setDbStories(stories);
      setHidden(new Set(hiddenIds));
    });
    return () => {
      cancelled = true;
    };
  }, [difficulty]);

  const staticBySlug = new Map(staticGroups.map((g) => [g.slug, g]));
  const dbGroups = dbStories.map((s) => {
    const fallback = staticBySlug.get(s.storyId);
    return dbStoryToGroup(s, fallback?.category ?? 'general', fallback?.cover);
  });

  return mergeStoryGroups(staticGroups, dbGroups, hidden);
}

/**
 * The rule for what a student sees, kept pure so it can be tested without
 * mounting a hook — it decides whether content appears at all.
 *
 * Two separate mechanisms, deliberately not conflated:
 *
 *   override — a published DB story REPLACES the static entry of the same slug,
 *              so an imported-and-edited story appears once, not twice.
 *   hidden   — takes a story out of the list entirely, and applies to both
 *              sides. This is the only thing that can remove a BUILT-IN story:
 *              those are declared in storyGroupsRaw and render whatever the
 *              database says, which is why deleting a draft never removed one
 *              (it dropped the override and the static entry came back).
 */
export function mergeStoryGroups(
  staticGroups: StoryGroup[],
  dbGroups: StoryGroup[],
  hidden: Set<string>,
): StoryGroup[] {
  const dbSlugs = new Set(dbGroups.map((g) => g.slug));
  return [...staticGroups.filter((g) => !dbSlugs.has(g.slug)), ...dbGroups].filter(
    (g) => !hidden.has(g.slug),
  );
}

// Single-story lookup with DB fallback. `loading` is true only while nothing
// is available to show yet (a slug that isn't a static story, still waiting
// on the DB check) — callers should wait for loading to clear before
// treating a missing storyGroup as "not found" (avoids a false redirect).
// A published DB story overrides its static counterpart once the fetch
// resolves, without blocking the initial render for existing content.
export function useStoryGroup(
  difficulty: DifficultySlug,
  slug: string,
  t: TFunction,
): { storyGroup: StoryGroup | undefined; loading: boolean } {
  const staticGroup = getStoryGroup(difficulty, slug, t);
  const [dbGroup, setDbGroup] = useState<StoryGroup | undefined>(undefined);
  const [dbChecked, setDbChecked] = useState(false);
  const [hidden, setHidden] = useState<Set<string>>(() => new Set());

  useEffect(() => {
    let cancelled = false;
    setDbChecked(false);
    // Both, because a story can be hidden without having a DB doc at all —
    // hiding is the only control that works on the built-in stories.
    Promise.all([
      fetchPublishedStory(difficulty, slug),
      fetchPublishedStoriesList(difficulty),
    ])
      .then(([story, list]) => {
        if (cancelled) return;
        setDbGroup(
          story
            ? dbStoryToGroup(story, staticGroup?.category ?? 'general', staticGroup?.cover)
            : undefined,
        );
        setHidden(new Set(list.hidden));
        setDbChecked(true);
      })
      .catch(() => {
        if (!cancelled) setDbChecked(true);
      });
    return () => {
      cancelled = true;
    };
    // staticGroup is derived from difficulty/slug/t and only supplies fallback
    // values; re-running on its identity would refetch on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [difficulty, slug]);

  // Hidden applies here too. useStoryGroups filtered the list while this hook
  // did not, so a hidden story vanished from the shelves but was still fully
  // reachable by URL — including from a bookmark or the level grid.
  const group = dbGroup ?? staticGroup;
  return {
    storyGroup: group && hidden.has(group.slug) ? undefined : group,
    loading: !staticGroup && !dbChecked,
  };
}