import { TFunction } from 'i18next';
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  fetchPublishedStoriesList,
  fetchPublishedStory,
  type PublishedStoryListItem,
} from '../services/storyServices';
import { useEntitlements } from '../context/EntitlementsContext';
import { useAuth } from '../context/AuthContext';
import { storyKey } from '../config/priceCatalog';
import { useCatalog } from '../context/CatalogContext';
import type { CatalogStory } from '../services/catalogServices';

export type StoryCategory = 'general' | 'news';

export interface StoryGroup {
  slug: string;           // URL-friendly name, e.g. "leo"
  title: string;
  description: string;
  character: string;
  totalTracks: number;
  coverEmoji: string;
  /**
   * 4:5 cover art for the story card in List.tsx, cropped from the story's own
   * first comic page. Generated by scripts/make-covers.py — run it after adding
   * a story so the card gets art instead of the halftone + emoji fallback.
   * Stories without one (news placeholders, anything built in the Story
   * Builder) fall back to coverEmoji, which is by design, not a gap.
   */
  cover?: string;
  /** Which heading/section this story is grouped under in List.tsx. Defaults to 'general'. */
  category: StoryCategory;
  /**
   * Paywall state. For a published DB story the SERVER decides it and carries
   * it on the list response; for a built-in story applyCatalogAccess() fills it
   * from the mirrored catalog. Undefined means the story is not sold.
   */
  locked?: boolean;
  /** Any one of these SKUs unlocks it, smallest scope first. */
  requiredSkus?: string[];
  /** When locked: parts 1..freeParts play in full. */
  freeParts?: number;
  /** When locked and set: part 1 is a timed preview of this many seconds. */
  previewSeconds?: number | null;
}

/**
 * Fills a BUILT-IN story's paywall fields from the price catalog.
 *
 * The server's list endpoint only knows published DB stories, so a static
 * story would otherwise arrive with no lock at all and look free. Pure, so the
 * rule can be tested without mounting anything.
 */
export function applyCatalogAccess(
  group: StoryGroup,
  difficulty: DifficultySlug,
  owned: boolean,
  catalog: {
    getCatalogStory: (key: string) => CatalogStory | null;
    skusGranting: (key: string) => string[];
    /** Optional so existing callers and tests keep the paywall on. */
    paywallEnabled?: boolean;
  },
  /** Is anyone signed in? Only meaningful while the paywall is off. */
  authenticated = false,
): StoryGroup {
  const key = storyKey(difficulty, group.slug);
  const entry = catalog.getCatalogStory(key);
  // Not in the catalog: no admin has listed it, so there is nothing to sell and
  // nothing to play. Left locked with no SKU rather than passed through
  // untouched — an untouched group has `locked: undefined`, which every shelf
  // reads as "owned", and that is how unlisted stories used to appear free.
  if (!entry) return { ...group, locked: true, requiredSkus: [], freeParts: 0, previewSeconds: null };
  // A story the catalog gives away is open to everyone, signed in or not.
  if (!entry.paid) {
    return {
      ...group,
      locked: false,
      requiredSkus: [],
      freeParts: group.totalTracks,
      previewSeconds: null,
    };
  }
  if (owned) {
    return { ...group, locked: false, requiredSkus: [], freeParts: group.totalTracks, previewSeconds: null };
  }
  // Nothing is sold at the moment, so an ACCOUNT is what opens the catalogue.
  //
  // This is the client's copy of the server's rule (accessFor), and it exists
  // for the stories that have no published DB row — maya, daniel and the rest
  // arrive from the static catalogue with no `locked` from the server at all.
  // Without this the page would padlock a signed-in user out of content the
  // server is perfectly willing to serve, because `owned` is false for
  // everyone: nobody has bought anything.
  if (catalog.paywallEnabled === false) {
    return authenticated
      ? { ...group, locked: false, requiredSkus: [], freeParts: group.totalTracks, previewSeconds: null }
      : { ...group, locked: true, requiredSkus: [], freeParts: entry.freeParts, previewSeconds: entry.previewSeconds };
  }
  // The row's own allowance, which may override the length-derived default.
  return {
    ...group,
    locked: true,
    requiredSkus: catalog.skusGranting(key),
    freeParts: entry.freeParts,
    previewSeconds: entry.previewSeconds,
  };
}

export type DifficultySlug = 'easy' | 'medium' | 'hard';
// Only non-translatable fields live here
type StoryGroupRaw = Omit<StoryGroup, 'title' | 'description' | 'category'> & {
  category?: StoryCategory;
};

const storyGroupsRaw: Record<DifficultySlug, StoryGroupRaw[]> = {
  easy: [
    { slug: 'leo', character: 'Leo', totalTracks: 10, coverEmoji: '🧑', cover: '/assets/covers/leo.jpg' },
    // totalTracks must match the real length of the track array in
    // audiodata/audioDataLeoAdditional.ts — a third track is drafted there but
    // commented out, and claiming 3 here meant progress could never reach 100%.
    { slug: 'leo-additional',    character: 'Leo',    totalTracks: 2, coverEmoji: '🧑', cover: '/assets/covers/leo-additional.jpg' },
    // Placeholder "News and Interesting things" group — students listen to a news
    // source/article first, then get a story connected to it. No real audio/text yet;
    // fill in totalTracks, coverEmoji, and src/modules/audiodata placeholder tracks
    // once content is ready.
    { slug: 'news-roland-garros', character: 'Leo', totalTracks: 2, coverEmoji: '📰', category: 'news', cover: '/assets/covers/news-roland-garros.jpg' },
    // No artwork yet, so no cover — this one keeps the halftone + emoji card.
    { slug: 'news-family-visit',  character: 'Leo', totalTracks: 2, coverEmoji: '📰', category: 'news' },
    { slug: 'news-grazing-board', character: 'Leo', totalTracks: 2, coverEmoji: '📰', category: 'news', cover: '/assets/covers/news-grazing-board.jpg' },
  ],
  medium: [
    { slug: 'maya',   character: 'Maya',   totalTracks: 10, coverEmoji: '👩', cover: '/assets/covers/maya.jpg' },
  ],
  hard: [
    { slug: 'daniel', character: 'Daniel', totalTracks: 10, coverEmoji: '👨', cover: '/assets/covers/daniel.jpg' },
  ],
};

/**
 * Each level's character art, used when a story has no cover of its own.
 *
 * Every story on a level stars the same character, so their own comic is the
 * honest stand-in — far better than the halftone placeholder, and it means the
 * nine extension-pack stories can ship without waiting on nine new comics to be
 * drawn. StoryCard crops each card differently (deterministically, from the
 * slug), so four Leo stories do not render as four identical cards.
 *
 * News stories are deliberately excluded below: they are not about the
 * character, and giving them his portrait would say something untrue about
 * what is inside. They keep the halftone + newspaper icon.
 */
export const CHARACTER_COVER: Record<DifficultySlug, string> = {
  easy: '/assets/covers/leo.jpg',
  medium: '/assets/covers/maya.jpg',
  hard: '/assets/covers/daniel.jpg',
};

/** A story's cover, falling back to its level's character art. */
export const coverFor = (
  difficulty: DifficultySlug,
  category: StoryCategory,
  ownCover?: string,
): string | undefined =>
  ownCover ?? (category === 'news' ? undefined : CHARACTER_COVER[difficulty]);

export const getStoryGroups = (diff: DifficultySlug, t: TFunction): StoryGroup[] =>
  storyGroupsRaw[diff].map(story => ({
    ...story,
    category:    story.category ?? 'general',
    title:       t(`stories.${diff}.${story.slug}.title`),
    description: t(`stories.${diff}.${story.slug}.description`),
  }));

// Single-story lookup — built on the same translated data as getStoryGroups,
// so a story's title/description never drifts from what List.tsx shows.
export const getStoryGroup = (
  difficulty: DifficultySlug,
  slug: string,
  t: TFunction,
): StoryGroup | undefined =>
  getStoryGroups(difficulty, t).find(group => group.slug === slug);

// ── DB-backed story fallback ────────────────────────────────────────────────
// Static stories (leo, leo-additional, maya, daniel, the news placeholders)
// are always available synchronously from the functions above, so these
// hooks return that same data immediately (no loading flash for existing
// content) and swap in a published DB-backed story once fetched — a DB
// story *overrides* its static counterpart by slug (imported+published
// stories replace the built-in entry instead of appearing twice), matching
// the whole-story "DB wins once published" precedence in the backend's
// helpers/storyLookup.js.

/**
 * @param fallbackCategory the static entry's category, used when the DB story
 *   has no opinion. A published DB story REPLACES its static counterpart
 *   wholesale, so hardcoding 'general' here silently moved every news story to
 *   the Stories shelf the moment it was published. Stories imported before the
 *   category field existed carry null, and this is what keeps them in place
 *   without a data migration.
 */
export type AppLocale = 'en' | 'ru';

/**
 * Which locale's text to show. i18next language codes can carry a region
 * ("ru-RU"), so match on the prefix rather than equality — the app only ever
 * ships these two bundles.
 */
function useAppLocale(): AppLocale {
  const { i18n } = useTranslation();
  return i18n.language?.toLowerCase().startsWith('ru') ? 'ru' : 'en';
}

function dbStoryToGroup(
  story: {
    storyId: string;
    storyName: string;
    description: string;
    localized?: { title: { en: string; ru: string }; description: { en: string; ru: string } } | null;
    characterIcon: string;
    category?: StoryCategory | null;
    coverUrl?: string | null;
    totalParts: number;
    locked?: boolean;
    requiredSkus?: string[];
    freeParts?: number;
    previewSeconds?: number | null;
  },
  fallbackCategory: StoryCategory = 'general',
  fallbackCover?: string,
  locale: AppLocale = 'en',
): StoryGroup {
  return {
    slug: story.storyId,
    // Per-locale text wins; storyName is the admin-facing identifier and only
    // stands in for stories imported before localized existed.
    title: story.localized?.title?.[locale]?.trim() || story.storyName,
    description: story.localized?.description?.[locale]?.trim() || story.description,
    character: story.storyName,
    totalTracks: story.totalParts,
    coverEmoji: story.characterIcon,
    category: story.category ?? fallbackCategory,
    // Same fallback as the category, for the same reason: publishing replaces
    // the static entry, so without this the card loses its art and drops back
    // to the halftone + emoji placeholder.
    cover: story.coverUrl ?? fallbackCover,
    locked: story.locked ?? false,
    requiredSkus: story.requiredSkus ?? [],
    freeParts: story.freeParts,
    previewSeconds: story.previewSeconds ?? null,
  };
}

/**
 * What the published-list endpoint last said, per difficulty, for the life of
 * the tab.
 *
 * This exists so a SECOND visit to a level costs no skeleton: the answer is
 * already here on the very first render, and the page paints its final state
 * straight away. Entering a level, going back, and entering it again is the
 * single most common path through this app, so the cheap case should be the
 * common one.
 *
 * It is stale-while-revalidate, not a plain cache — every mount still refetches
 * in the background and overwrites this. So a story published from the Story
 * Builder shows up on the next navigation rather than needing a reload, and the
 * worst a stale entry can do is render one frame of a list that was correct a
 * moment ago. Nothing here is an entitlement decision: `locked` is the server's
 * word, and a cached `locked: false` cannot unlock anything, because the player
 * asks the server for audio and gets refused independently of this.
 */
//
// Keyed by WHO asked as well as which level. The response carries each story's
// lock state for the caller, so a list cached while signed out, or signed in as
// someone else, painted that person's padlocks first and then the real ones.
const publishedListCache = new Map<
  string,
  { stories: PublishedStoryListItem[]; hidden: Set<string> }
>();

/**
 * The newest request per cache key. Responses can arrive out of order — React
 * StrictMode mounts twice, and a slow request can finish after a quick
 * navigation away and back — and an overtaken answer must not overwrite the
 * cache, or the NEXT visit opens on a shelf that was already out of date.
 */
const latestRequest = new Map<string, number>();
let requestSeq = 0;

// Stable identities for "the server has not answered yet". A fresh `[]` or
// `new Set()` is a different object every time it is evaluated, so handing one
// to setState always counts as a change — which bought a whole extra render
// that repainted the identical skeleton. Neither is ever mutated: a resolved
// fetch builds its own Set.
const NO_STORIES: PublishedStoryListItem[] = [];
const NO_HIDDEN: Set<string> = new Set();

/**
 * The level's stories, plus whether the server has answered yet.
 *
 * `loading` is the whole point. Without it a page has no way to tell the
 * difference between "these are the stories" and "these are the stories I
 * could name before asking", and every caller painted the latter: the static
 * catalogue rendered first, unlocked and complete, then snapped to the real
 * list a moment later as padlocks appeared, hidden stories vanished and
 * published ones arrived. The data was never wrong, it was just shown before
 * it was true.
 */
export function useStoryGroupsWithStatus(
  difficulty: DifficultySlug,
  t: TFunction,
): { stories: StoryGroup[]; loading: boolean } {
  const locale = useAppLocale();
  const { owns, entitlementsLoading } = useEntitlements();
  const catalog = useCatalog();
  const { user } = useAuth();
  const cacheKey = `${user?.id ?? 'guest'}:${difficulty}`;
  // Memoised so the static catalogue has one identity per (level, language)
  // rather than a new array per render — which is what lets the merge at the
  // bottom of this hook depend on it honestly instead of listing a subset of
  // its real inputs and silencing the lint rule.
  const staticGroups = useMemo(() => getStoryGroups(difficulty, t), [difficulty, t]);
  // The RAW rows are held in state and adapted during render, not in the
  // effect: adapting needs the static entry's category as a fallback, and
  // reaching for staticGroups inside the effect would either capture a stale
  // copy or, if listed as a dependency, refetch on every render since
  // getStoryGroups builds a new array each time.
  //
  // Seeded from the cache in the initialiser rather than by an effect, which is
  // what makes a repeat visit flicker-free: by the time the first render runs,
  // the state already holds the answer.
  const seed = publishedListCache.get(cacheKey);
  const [dbStories, setDbStories] = useState<PublishedStoryListItem[]>(
    () => seed?.stories ?? NO_STORIES,
  );
  const [hidden, setHidden] = useState<Set<string>>(() => seed?.hidden ?? NO_HIDDEN);
  const [loading, setLoading] = useState(() => !seed);

  // Switching levels resets during render, not in an effect.
  //
  // /levels/easy → /levels/medium is the same route element with a new param,
  // so React keeps this component mounted. An effect would only correct the
  // state AFTER a frame had been painted, and that frame is medium's static
  // catalogue merged with easy's published rows — a list that has never been
  // true. Assigning during render makes React throw the in-progress output
  // away and start again before anything reaches the screen.
  // Signing in or out changes the key too, and gets the same treatment.
  const [loadedFor, setLoadedFor] = useState<string>(cacheKey);
  if (loadedFor !== cacheKey) {
    const known = publishedListCache.get(cacheKey);
    setLoadedFor(cacheKey);
    setDbStories(known?.stories ?? NO_STORIES);
    setHidden(known?.hidden ?? NO_HIDDEN);
    // A level already in the cache never drops back to a skeleton.
    setLoading(!known);
  }

  useEffect(() => {
    let cancelled = false;
    requestSeq += 1;
    const requestId = requestSeq;
    latestRequest.set(cacheKey, requestId);

    fetchPublishedStoriesList(difficulty).then(({ stories, hidden: hiddenIds, ok }) => {
      // Overtaken by a newer request for the same list: this is older news.
      if (latestRequest.get(cacheKey) !== requestId) return;

      const known = publishedListCache.get(cacheKey);
      // A failed fetch comes back empty. Painting that over a list we already
      // hold swapped the real shelf for the bare static catalogue until the
      // next successful request put it back.
      if (!ok && known) {
        if (!cancelled) setLoading(false);
        return;
      }

      const hiddenSet = new Set(hiddenIds);
      // Cached even if this hook has unmounted in the meantime — but only a
      // real answer, never a failure.
      if (ok) publishedListCache.set(cacheKey, { stories, hidden: hiddenSet });
      if (cancelled) return;
      setDbStories(stories);
      setHidden(hiddenSet);
      setLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, [difficulty, cacheKey]);

  // Memoised because this used to hand back a freshly built array on EVERY
  // render — new identity, same contents — which defeated the useMemo in
  // List.tsx that depends on it and made every card's props new each time.
  const stories = useMemo(() => {
    const staticBySlug = new Map(staticGroups.map((g) => [g.slug, g]));
    const dbGroups = dbStories.map((s) => {
      const fallback = staticBySlug.get(s.storyId);
      const category = s.category ?? fallback?.category ?? 'general';
      return dbStoryToGroup(
        s,
        fallback?.category ?? 'general',
        coverFor(difficulty, category, fallback?.cover),
        locale,
      );
    });
    const staticWithAccess = staticGroups.map((g) =>
      applyCatalogAccess(g, difficulty, owns(difficulty, g.slug), catalog, Boolean(user)),
    );
    return mergeStoryGroups(staticWithAccess, dbGroups, hidden);
    // `catalog` belongs here: it arrives asynchronously, and without it this
    // memo keeps the answer it computed against an EMPTY catalog — every
    // built-in story locked with no SKU — for the life of the page.
  }, [staticGroups, difficulty, locale, dbStories, hidden, owns, catalog]);

  // A lock drawn before ownership is known is a lock that flickers off.
  // A price or a padlock drawn before the catalog lands is one that changes
  // under the reader, so the catalog is part of "not ready yet" too.
  return { stories, loading: loading || entitlementsLoading || catalog.catalogLoading };
}

/**
 * The stories alone, for callers that are happy to paint the static catalogue
 * first and correct it a moment later.
 */
export function useStoryGroups(difficulty: DifficultySlug, t: TFunction): StoryGroup[] {
  return useStoryGroupsWithStatus(difficulty, t).stories;
}

/**
 * The rule for what a student sees, kept pure so it can be tested without
 * mounting a hook — it decides whether content appears at all.
 *
 * Two separate mechanisms, deliberately not conflated:
 *
 *   override — a published DB story REPLACES the static entry of the same slug,
 *              so an imported-and-edited story appears once, not twice.
 *   hidden   — takes a story out of the list entirely, and applies to both
 *              sides. This is the only thing that can remove a BUILT-IN story:
 *              those are declared in storyGroupsRaw and render whatever the
 *              database says, which is why deleting a draft never removed one
 *              (it dropped the override and the static entry came back).
 */
export function mergeStoryGroups(
  staticGroups: StoryGroup[],
  dbGroups: StoryGroup[],
  hidden: Set<string>,
): StoryGroup[] {
  const dbSlugs = new Set(dbGroups.map((g) => g.slug));
  return [...staticGroups.filter((g) => !dbSlugs.has(g.slug)), ...dbGroups].filter(
    (g) => !hidden.has(g.slug),
  );
}

// Single-story lookup with DB fallback. `loading` is true only while nothing
// is available to show yet (a slug that isn't a static story, still waiting
// on the DB check) — callers should wait for loading to clear before
// treating a missing storyGroup as "not found" (avoids a false redirect).
// A published DB story overrides its static counterpart once the fetch
// resolves, without blocking the initial render for existing content.
export function useStoryGroup(
  difficulty: DifficultySlug,
  slug: string,
  t: TFunction,
): { storyGroup: StoryGroup | undefined; loading: boolean } {
  const staticGroup = getStoryGroup(difficulty, slug, t);
  const [dbGroup, setDbGroup] = useState<StoryGroup | undefined>(undefined);
  const [dbChecked, setDbChecked] = useState(false);
  const [hidden, setHidden] = useState<Set<string>>(() => new Set());
  const locale = useAppLocale();
  const { owns } = useEntitlements();
  const catalog = useCatalog();
  const { user } = useAuth();

  useEffect(() => {
    let cancelled = false;
    setDbChecked(false);
    // Both, because a story can be hidden without having a DB doc at all —
    // hiding is the only control that works on the built-in stories.
    Promise.all([
      fetchPublishedStory(difficulty, slug),
      fetchPublishedStoriesList(difficulty),
    ])
      .then(([story, list]) => {
        if (cancelled) return;
        setDbGroup(
          story
            ? dbStoryToGroup(
                story,
                staticGroup?.category ?? 'general',
                coverFor(difficulty, staticGroup?.category ?? 'general', staticGroup?.cover),
                locale,
              )
            : undefined,
        );
        setHidden(new Set(list.hidden));
        setDbChecked(true);
      })
      .catch(() => {
        if (!cancelled) setDbChecked(true);
      });
    return () => {
      cancelled = true;
    };
    // staticGroup is derived from difficulty/slug/t and only supplies fallback
    // values; re-running on its identity would refetch on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [difficulty, slug]);

  // Hidden applies here too. useStoryGroups filtered the list while this hook
  // did not, so a hidden story vanished from the shelves but was still fully
  // reachable by URL — including from a bookmark or the level grid.
  const group =
    dbGroup ??
    (staticGroup &&
      applyCatalogAccess(
        staticGroup,
        difficulty,
        owns(difficulty, staticGroup.slug),
        catalog,
        Boolean(user),
      ));
  return {
    storyGroup: group && hidden.has(group.slug) ? undefined : group,
    loading: !staticGroup && !dbChecked,
  };
}