// GENERATED FILE — DO NOT EDIT BY HAND.
// Run: node scripts/generate-vocab-keys.mjs
//
// Every vocabulary progress key in the legacy (bundled) story catalogue, which
// is the only vocabulary the backend cannot otherwise see: those decks live in
// the frontend's src/modules/vocabulary/Vocabulary.ts and are never sent to the
// server. DB-authored stories are validated against the Story model at request
// time instead, so they are deliberately absent here.
//
// Keys are already lowercased and trimmed, matching what the player reports —
// `(audioKey ?? word).toLowerCase()`, see VocabChip.tsx.
//
// Source bytes at generation time: 52334
// Entries: 499

export const LEGACY_VOCAB_KEYS = new Set([
  "a beach",
  "a career grand slam",
  "a castle",
  "a champion",
  "a coach",
  "a dish",
  "a dress",
  "a gift",
  "a grand slam",
  "a grazing board",
  "a habit",
  "a link",
  "a lot of friends",
  "a pasture",
  "a pile",
  "a quiet morning",
  "a racket",
  "a rising star",
  "a runner-up",
  "a schoolgirl",
  "a shark",
  "a sharp knife",
  "a shore",
  "a survey",
  "a ticket",
  "a tight budget",
  "a tip",
  "a title",
  "a tournament",
  "a trip",
  "a usual day",
  "a wooden board",
  "a world championship",
  "abandoned mug",
  "accumulate debt",
  "adventures",
  "affordable",
  "affordable accommodation",
  "airplane mode",
  "airway bill",
  "allocate funds",
  "almost",
  "altar",
  "alternative route",
  "amazing",
  "an alternative",
  "an exchange rate",
  "ancestral memory",
  "anchor",
  "ancient festival",
  "ancient temples",
  "answer",
  "antipasti",
  "apple pie",
  "art gallery",
  "artisan",
  "assignment",
  "at all",
  "attacker",
  "attend",
  "auction",
  "authentic",
  "bakery",
  "baseline wages",
  "be about",
  "be down for",
  "be good at",
  "be kidding",
  "be out",
  "be scarce",
  "be tired of",
  "believe in",
  "bend over",
  "bet on",
  "blanket",
  "bloodstream",
  "blush",
  "bollard",
  "borrowed",
  "boundary",
  "brace for",
  "break down",
  "brittle",
  "brush my teeth",
  "business",
  "busy",
  "cadence",
  "cafe",
  "calendar collisions",
  "call up",
  "cannibalize",
  "cap",
  "captivated",
  "carefully",
  "catch up",
  "catch up on",
  "cathedral",
  "celebrate",
  "ceremony",
  "change",
  "change your mind",
  "check out",
  "cherry tomatoes",
  "choreography",
  "claw back",
  "coastal town",
  "coastal village",
  "cold appetizers",
  "cold-chain facility",
  "colonise",
  "come back",
  "come in handy",
  "come true",
  "come up",
  "comfortable",
  "communally",
  "compensate",
  "complain",
  "compose yourself",
  "compound effort",
  "compound interest",
  "confess",
  "connecting train",
  "consistent",
  "controllable",
  "convenience shop",
  "convenient",
  "cool down",
  "coordination",
  "cost of living",
  "cousin",
  "cozy",
  "craft",
  "crafts",
  "craftsman",
  "cringe",
  "curious",
  "customs broker",
  "dangerous",
  "dating",
  "deadlock",
  "declare a red day",
  "declare a rule",
  "declining fish stocks",
  "defeat",
  "delayed",
  "detailed budget",
  "detour",
  "discipline",
  "discount",
  "dispatcher",
  "diverse perspectives",
  "do about",
  "dough",
  "drastically",
  "dream come true",
  "drinking water",
  "dry-cured sausage",
  "duck into",
  "duplicate entries",
  "dvd collection",
  "early bird",
  "eat",
  "eat out",
  "efficiency",
  "elders",
  "end up",
  "enthusiasm",
  "environmental pollution",
  "error rates",
  "every day",
  "exams",
  "expand into",
  "explosion of flavors",
  "expressive",
  "eye-opening",
  "face to face",
  "fall for",
  "fall into",
  "family council",
  "fangs",
  "fashionable",
  "feed",
  "feed up",
  "filling",
  "finances",
  "find out",
  "flat",
  "flawlessly",
  "flexibility",
  "fly by",
  "fold into",
  "fold-out chair",
  "follow",
  "follow along",
  "follow sports",
  "fragility",
  "freak squall",
  "fried insect",
  "friendly",
  "from scratch",
  "fuel hedges",
  "fumed",
  "gelato",
  "get carried away",
  "get involved in",
  "get lost",
  "get out of bed",
  "get the beatings",
  "get up",
  "gift",
  "go back",
  "go down",
  "go in",
  "go on",
  "go straight to",
  "go to waste",
  "gondola",
  "goodwill",
  "got promoted",
  "grace",
  "grade",
  "grapes",
  "graze",
  "grounding",
  "grow up",
  "grudgingly",
  "guess",
  "ham",
  "hand signals",
  "handmade",
  "hard work",
  "harmonized chant",
  "harvest time",
  "hazard pay",
  "hear from",
  "herring",
  "hesitantly",
  "hierarchy",
  "highlands",
  "honey",
  "hostel",
  "hotshot",
  "humility",
  "important",
  "impromptu",
  "in love",
  "incredibly",
  "inform",
  "insane",
  "inspiring",
  "instead",
  "instructive",
  "integrity",
  "interchangeable",
  "intern",
  "invite over",
  "irregular hours",
  "join in",
  "journalist",
  "just",
  "keep doing",
  "keep from",
  "keynote",
  "kind",
  "lark",
  "lasagna",
  "lateral swap",
  "laugh",
  "lay down",
  "legendary",
  "lie",
  "lie down",
  "livelihood",
  "local shop",
  "lodging",
  "logistic nightmare",
  "logistics",
  "look around",
  "look back",
  "look for",
  "lucky socks",
  "make a move on",
  "make a wish",
  "make it through",
  "make up",
  "medical equipment",
  "mediterranean food",
  "meet up",
  "mentor",
  "microplastic",
  "midnight",
  "milky way",
  "mint tea",
  "mismatch",
  "miss",
  "missed a handover",
  "most",
  "navigate",
  "near",
  "neat and tidy",
  "neighborhood",
  "neon lights",
  "netflix series",
  "night owl",
  "nightlife",
  "notable",
  "notice",
  "obviously",
  "offerings",
  "old friend",
  "older",
  "olives",
  "on hand",
  "online magazine",
  "only",
  "optimization",
  "outfit",
  "overtime",
  "owner",
  "pallets",
  "panpipes",
  "pass down",
  "pass on",
  "passionate",
  "pastries",
  "patient",
  "patterns",
  "pay for",
  "payroll",
  "peak yield",
  "peel",
  "percent",
  "performance logs",
  "pick up",
  "pictures",
  "pilot phase",
  "plans for the future",
  "plastic waste",
  "play games",
  "post",
  "posters",
  "practically",
  "practice",
  "prepare",
  "pretty good",
  "prices spiked",
  "procession",
  "productive",
  "promenade",
  "put away",
  "put on",
  "put out",
  "put together",
  "put up",
  "quail eggs",
  "quay",
  "railway station",
  "raise a glass",
  "razor-thin margins",
  "recall",
  "reconcile",
  "recorder",
  "reefer",
  "reflect",
  "relax",
  "remind",
  "remote villages",
  "renegotiate",
  "reporter's id",
  "reroute",
  "resilience",
  "respect",
  "retention schemes",
  "revenge",
  "reverse gear",
  "rise up",
  "ritual",
  "roll in",
  "run away",
  "run into",
  "rye bread",
  "sacred",
  "safe",
  "said goodbye",
  "sail through",
  "sales are going down",
  "saving money",
  "scanner hiccup",
  "scans",
  "scared",
  "schedule",
  "sense of belonging",
  "serene",
  "serious relationship",
  "service level agreement",
  "set up",
  "shake",
  "share experiences",
  "shipment",
  "shrine",
  "sign off",
  "single-lane bridge",
  "slice",
  "smoked cheese",
  "social media",
  "soft",
  "souvenirs",
  "spend on",
  "sports field",
  "sprats",
  "spread across the world",
  "staff turnover",
  "staggered delivery windows",
  "staggered retreat",
  "start up",
  "staying connected",
  "step into",
  "stomach bug",
  "stranded",
  "stressful",
  "structural advantages",
  "sturdiness",
  "suit",
  "sweaty",
  "swim back",
  "swimming suit",
  "take a guess",
  "take measures",
  "take off",
  "take out",
  "taste buds",
  "taught himself",
  "team captain",
  "tears of joy",
  "temperature fluctuations",
  "term paper",
  "thank for",
  "the final",
  "the oven",
  "the youngest",
  "think about",
  "thrill",
  "time zones",
  "time-critical",
  "tiny",
  "to spend",
  "together",
  "torches",
  "toss in",
  "track spending",
  "traditional",
  "traditional customs",
  "translation app",
  "transparency",
  "travel",
  "trek",
  "trends",
  "trousers",
  "trout",
  "trust",
  "trust but verify",
  "turn into",
  "turn out",
  "typo",
  "unfair",
  "unhealthy",
  "uniform",
  "unwind",
  "upset",
  "upskilling",
  "utilisation",
  "variance",
  "vendetta",
  "veteran operator",
  "veterinarian",
  "vibrant atmosphere",
  "voice memos",
  "voice note",
  "volatile compound",
  "volatility",
  "vulnerability",
  "wake up",
  "walnuts",
  "wander",
  "warehouse",
  "warm up",
  "wave of panic",
  "weaponize",
  "wedged",
  "wonderful",
  "woolen sweater",
  "work for",
  "work trip",
  "workshop",
  "worst-case scenario",
  "woven textiles",
  "write down",
  "young"
]);
